services:
  mysql:
    container_name: 'user-items-mysql'
    image: 'mysql:9.2.0'
    environment:
      - 'MYSQL_DATABASE=useritems'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'