  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/useritems
      username: admin
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true