server:
  servlet:
    context-path: /v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/useritems
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

jwt:
  secret: "${JWT_SECRET:supersecretkeysupersecretkeysupersecretkeysupersecretkey}"